# Generated by Django 4.0.6 on 2022-09-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orders_order_rename_ordersfood_orderfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Shop',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Shop',
            new_name='shop',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_time',
            field=models.IntegerField(default=-1),
        ),
    ]
